Fix : #234 Missing checks for address(0x0) when updating address stat…
ArkProjectNFTs/bridge pull request #240
Opened 2024-09-27 16:47 UTC by ryzen-xp

Summary of Changes Made
Input Validation in setL1L2CollectionMapping:
Added checks to ensure collectionL1 is not address(0) and collectionL2 is not 0 to prevent invalid mappings. Event Emission:
Emitted L1L2CollectionMappingUpdated after setting the mapping for transparency.

and  add unit test

2024-09-28 15:44 UTC, ptisserand requested changes
Thanks for your PR!
Only minor changes and it will good to be merged

2024-09-28 15:44 UTC, ptisserand commented on apps/blockchain/ethereum/test/Bridge.t.sol
> +    function testInvalidL1Address() public {
Could you please change the test name to reflect it's checking `setL1L2CollectionMapping`

2024-09-28 15:44 UTC, ptisserand commented on apps/blockchain/ethereum/test/Bridge.t.sol
> +    function testInvalidL2Address() public {
Could you please change the test name to reflect it's checking `setL1L2CollectionMapping`

2024-09-28 15:44 UTC, ptisserand commented on apps/blockchain/ethereum/test/Bridge.t.sol
> +    function testInvalidUnwrappedL2Address() public {
Could you please change the test name to reflect it's checking `setL1L2CollectionMapping`

2024-09-28 17:26 UTC, ryzen-xp commented
Hello Sir @ptisserand  , 
            I change all  test name  , Can you recheck my PR request .     
        Thanks!

2024-09-30 07:35 UTC, ptisserand requested changes
Please use custom error instead of require

2024-09-30 07:35 UTC, ptisserand commented on apps/blockchain/ethereum/src/Bridge.sol
> +            require( collectionL1 != address(0x0), "Invalid L1 address");
Sorry I miss this part in my previous review.
Could you please use solidity custom errors instead as other error:
```solidity
error BridgeNotEnabledError();
// ....

        if (!_enabled) {
            revert BridgeNotEnabledError();
        }
```

2024-09-30 08:09 UTC, ryzen-xp commented
Hello Sir @ptisserand  ,
             I change  all  you want to change ,  Plz  Check my PR request .

2024-09-30 09:06 UTC, ptisserand requested changes

2024-09-30 09:06 UTC, ptisserand commented on apps/blockchain/ethereum/test/Bridge.t.sol
> +         vm.expectRevert(abi.encodeWithSignature("InvalidL1AddressError()"));
To match other tests, use:
```solidity
vm.expectRevert(InvalidL1AddressError.selector);
```

2024-09-30 09:06 UTC, ptisserand commented on apps/blockchain/ethereum/test/Bridge.t.sol
> +        vm.expectRevert(abi.encodeWithSignature("InvalidL2AddressError()"));
To match other tests, use:
```solidity
vm.expectRevert(InvalidL2AddressError.selector);
```

2024-09-30 09:53 UTC, ryzen-xp commented
@ptisserand  sir ,    can you  check again my PR plz.

2024-09-30 10:02 UTC, ptisserand approved these changes
Thanks for your contribution!

2024-09-30 10:03 UTC, merged

2024-09-30 10:07 UTC, ryzen-xp commented
Thank you Sir