add burn function
ArkProjectNFTs/bridge pull request #243
Opened 2024-09-29 03:52 UTC by mubarak23

2024-09-29 12:01 UTC, ybensacq commented
@mubarak23 could you keep the original formatting please ?

2024-09-29 12:54 UTC, mubarak23 commented
> @mubarak23 could you keep the original formatting please ?

Am using eslint, 

What formatting setup are you using this project

2024-09-30 07:45 UTC, ptisserand requested changes
Hi, unit tests are missing.

2024-09-30 07:57 UTC, mubarak23 commented
> Hi, unit tests are missing.

alright, wanted to make sure the implementation is correct, before proceeding to the unit test, 

i will push it right away

2024-10-02 06:38 UTC, ptisserand commented
> > Hi, unit tests are missing.
> 
> alright, wanted to make sure the implementation is correct, before proceeding to the unit test,
> 
> i will push it right away

Hi @mubarak23 any update on this ?

2024-10-02 06:47 UTC, mubarak23 commented
> > > Hi, unit tests are missing.
> > 
> > 
> > alright, wanted to make sure the implementation is correct, before proceeding to the unit test,
> > i will push it right away
> 
> Hi @mubarak23 any update on this ?

am having an issue with the test, i will fix it and push very soon

2024-10-02 07:25 UTC, mubarak23 commented
@ptisserand 

this is my test function 

```
    #[test]
fn burn_from_bridge() {
    let BRIDGE = bridge_addr_mock();
    
    let DUO_OWNER = starknet::contract_address_const::<128>();

    let contract_address = deploy_everai_collection();

    let erc721b = IERC721BridgeableDispatcher { contract_address };

    // Mint a token first to be able to burn it later
    start_prank(CheatTarget::One(contract_address), BRIDGE);
    erc721b.mint_from_bridge(DUO_OWNER, 42_u256);
    stop_prank(CheatTarget::One(contract_address));

    // Check that the owner is set correctly after minting
    let erc721 = IERC721Dispatcher { contract_address };
    assert!(erc721.owner_of(42_u256) == DUO_OWNER, "bad owner after mint");

    // Burn the token
    start_prank(CheatTarget::One(contract_address), BRIDGE);
    erc721b.burn(42_u256);
    stop_prank(CheatTarget::One(contract_address));

    // Verify that the token no longer exists
    let burn_result = erc721.owner_of(42_u256);
    assert!(burn_result == DUO_OWNER, "token should be burned, but still exists");
}
```

i keep getting the following error 

```
Failure data:
    0x4552433732313a20696e76616c696420746f6b656e204944 ('ERC721: invalid token ID')
```

2024-10-03 05:51 UTC, ptisserand requested changes
There is a really huge security issue to let anyone burn any token!
Please fix it

2024-10-03 05:51 UTC, ptisserand commented on apps/blockchain/starknet/src/token/erc721_bridgeable.cairo
> +        fn burn(ref self: ContractState, token_id: u256) {
You need to ensure that caller is the owner of the token before burning

2024-10-03 05:51 UTC, ptisserand commented on apps/blockchain/starknet/src/token/erc721_bridgeable.cairo
> +         start_prank(CheatTarget::One(contract_address), BRIDGE);
`balance_of` is a view so no need for prank here

2024-10-03 05:51 UTC, ptisserand commented on apps/blockchain/starknet/src/token/erc721_bridgeable.cairo
> +        start_prank(CheatTarget::One(contract_address), BRIDGE);
It doesn't make sense that bridge can burn a not owned token

2024-10-03 05:51 UTC, ptisserand commented on apps/blockchain/starknet/src/token/erc721_bridgeable.cairo
> +       let balance = erc721.balance_of(BRIDGE);
Wrong check,  token ID 42 is/was owned by DUO_OWNER

2024-10-04 14:39 UTC, ptisserand requested changes
Thanks!
After tests renaming, it could be merged.

2024-10-04 14:39 UTC, ptisserand commented on apps/blockchain/starknet/src/token/erc721_bridgeable.cairo
> +    }
Could you please rename the test since it's not really *burn from bridge* but instead of *regular* burn test

2024-10-04 14:39 UTC, ptisserand commented on apps/blockchain/starknet/src/token/erc721_bridgeable.cairo
> +    fn should_panic_burn_from_bridge() {
Same here, please rename this test

2024-10-07 22:15 UTC, ptisserand approved these changes
Thanks for your contribution

2024-10-07 22:16 UTC, merged